export const LINHAS_INICIAIS = [
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "5KG" },
  { kilo: "5KG" },
  { kilo: "5KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "10KG" },
  { kilo: "5KG" },
  { kilo: "5KG" },
  { kilo: "5KG" },
  { kilo: "0KG" }
];
